# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-27 22:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0002_auto_20171027_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attachments', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
    ]
