# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_auto_20180227_1424'),
        ('attachments', '0002_auto_20180104_1247'),
    ]

    operations = [
    ]
